/*
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: core-api-postgres
    restart: always
    environment:
      POSTGRES_USER: user_nest
      POSTGRES_PASSWORD: password_nest
      POSTGRES_DB: core_api_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  */